### ISSUE TITLE
missing pad_right and pad_left keywords

### ISSUE THREAD

**Issue by yuzh00007** [coli-saar/cl#1]
https://github.com/coli-saar/cl/blob/bb6070760ee14041704671cbb179c0f8e8a02600/a1/ngram.py#L60

to get the sample working, I needed to provide those keywords in this line here, cannot leave the args without specifying what they are.

**Comment by alexanderkoller** [comment]
Fixed in https://github.com/coli-saar/cl/commit/941bc9f358eaa98ca898a778751701231aeaf0c3. Thanks for bringing this to our attention!
