### ISSUE TITLE
Incorrect dataset subset on assignment 4

### ISSUE THREAD

**Issue by vietanh125** [coli-saar/cl#3]
On the assignment 4 wiki, the subset `de-gsd` of the [Universal Dependencies](https://huggingface.co/datasets/universal_dependencies) should be `de_gsd` (underscore instead of hyphen). Hence, this should work:

(redacted by AK)

**Comment by alexanderkoller** [comment]
Good catch, thanks!

**Comment by alexanderkoller** [comment]
PS Please don't post code that solves the assignment in a public place.
